<?php

namespace AppBundle\Repository;

/**
 * BCaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BCaseRepository extends \Doctrine\ORM\EntityRepository
{
}
